### ISSUE TITLE
Programming as Conversation: Statements Quiz

### ISSUE THREAD

**Issue by Jtheiss123** [learn-co-curriculum/programming-univbasics-2-quiz#1]
I went to complete the programming as conversation Statements Quiz and I have completed quiz yet. It is saying  I did with answers chosen even tho I have not attempted the quiz yet. Is there a way to clear the answers so I can complete it myself .

**Comment by sgharms** [comment]
Hi @Jtheiss123 

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson

**Comment by realAndrewCohn** [comment]
Hello @Jtheiss123 

I'm looking into this issue in Learn. Would you mind providing some more information about this bug as well as steps required to replicate it?

- Does this issue continue after refreshing the page?
- What are the steps required to reproduce the problem? Navigating from a lesson? Is there anything in particular that seems to trigger the issue?

Thanks!

**Comment by Jtheiss123** [comment]
I tried refreshing the quiz but answers are prefilled. I even followed the steps to  reset work and still no luck. 
Jacqueline Theiss 

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 8, 2019 at 2:40 PM, Andrew<notifications@github.com> wrote:   
Hello @Jtheiss123

I'm looking into this issue in Learn. Would you mind providing some more information about this bug as well as steps required to replicate it?
   
   - Does this issue continue after refreshing the page?
   - What are the steps required to reproduce the problem? Navigating from a lesson? Is there anything in particular that seems to trigger the issue?

Thanks!
